start call "./zookeeper.bat"
start call "./kafka_server1.bat"
start call "./kafka_server2.bat"
start call "./kafka_server3.bat"
start call "./kafka_server4.bat"
start call "./kafka_server5.bat"
start call "./kafka_server6.bat"
